version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expense_manager
    environment:
      POSTGRES_USER: dhruvil
      POSTGRES_PASSWORD: dhruvil
      POSTGRES_DB: expense_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhruvil -d expense_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: expense_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dhruvildhamsaniya123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dhruvil1731
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: .
    container_name: expense_backend
    environment:
      DATABASE_URL: postgresql://dhruvil:dhruvil@localhost:5432/expense_manager
      SECRET_KEY: 4369c3d4e59150ed720546c20dfaa143b27745c41956a73909e742142bb82dbe
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: